pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // Using bat for Windows command
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                // Using bat for Windows command
                bat 'mvn test'
            }
            post {
                always {
                    // JUnit plugin usage remains the same
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                // You need to convert deliver.sh to a Windows-compatible script
                // Assuming deliver.bat is the Windows batch script equivalent to deliver.sh
                bat 'call jenkins\\scripts\\deliver.bat'
            }
        }
    }
}

